dirot_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("shutafim.urls")),


]

shutafim/urls.py
from django.urls import path


from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_page, name="login_page"),
    path("register/", views.register_page, name="register_page"),
    path("logout/", views.logout_page, name="logout_page"),
    path("search/", views.search, name="search"),
    path("myads/", views.myads, name="myads"),
    path("apr/", views.single_page_view, name="single_page_view"),
    path("apr/<int:apr_id>", views.single_page_view, name="single_page_view"),
    path("ad/<int:apr_id>", views.newadd, name="newadd"),
    path("ad/", views.newadd, name="newadd"),
    path("api/delete/", views.delete_apr, name="delete_apr"),
    path("api/delete/<int:apr_id>", views.delete_apr, name="delete_apr"),
    path("api/", views.api, name="api"),
    path("api/<int:apr_id>", views.api, name="api"),
    path("send_mes/", views.send_email_to_publisher, name="send_email_to_publisher"),
    path("send_mes/<int:apr_id>", views.send_email_to_publisher, name="send_email_to_publisher"),
    path("vaild/", views.vaild_account, name="vaild_account"),
    path("vaild/<user_id>", views.vaild_account, name="vaild_account"),
    path("vaild/<user_id>/<token>", views.vaild_account, name="vaild_account"),
    path("rest_password/", auth_views.PasswordResetView.as_view(template_name = 'reset/password_reset.html', html_email_template_name='reset/password_reset_email.html'), name='reset_password'),
    path("rest_password_sent/", auth_views.PasswordChangeDoneView.as_view(), name='password_reset_done'),
    path("rest/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name = 'reset/password_confirm.html'), name='password_reset_confirm'),
    path("rest_password_complete/", auth_views.PasswordResetCompleteView.as_view(template_name = 'reset/password_reset_done.html'), name='password_reset_complete'),
    path("map/", views.map, name="map"),
    path("messages/", views.inbox, name="inbox"),
    path("renew/", views.renew_ad, name="renew"),
    path("renew/<int:apr_id>", views.renew_ad, name="renew"),
]

shutafim/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import datetime
from firebase_admin import credentials,initialize_app, storage
from django.conf import settings
import random

class Apartment(models.Model):
    publisher = models.ForeignKey(User, on_delete=models.CASCADE) 
    city = models.CharField(null=False, max_length=100)#
    street = models.CharField(max_length=100)#
    rent_price = models.IntegerField(default=0)#
    floor = models.IntegerField(default=0)#
    partners = models.IntegerField(default=0)#
    gender = models.IntegerField(default=0)#
    entry_date = models.DateField(default=datetime.date.today)#
    details = models.CharField(max_length=500, default='')
    title = models.CharField(max_length=24, default='')
    kosher = models.IntegerField(default=0)
    agree_mail = models.BooleanField(default=True)
    type = models.IntegerField(default=0)
    update = models.DateTimeField(default=timezone.now)

    def __str__(self):
        if self.street: return self.city + ', ' + self.street
        return self.city
    
    def get_url(self):
        return f'{settings.MY_URL}apr/{self.id}'
    
    def short_title(self):
      my_title = self.title
      if len(my_title)> 22: my_title = my_title[:22]+'...'
      elif not my_title: my_title = '  '
      return my_title
    
    def short_details(self):
      my_content = self.details
      if len(my_content)> 25: my_content = my_content[:25]+'...'
      elif not my_content: my_content = '  '
      return my_content
    
    def get_date_format(self):
        return self.entry_date.strftime('%d/%m/%Y')
    
    def get_first_img(self):
        if self.imagedata_set.all(): return self.imagedata_set.all()[0].myurl
        else: return 'https://firebasestorage.googleapis.com/v0/b/diro-ac902.appspot.com/o/no-image-icon-23500.jpg?alt=media&token=a1d5a015-bf2e-489d-988a-6e143a76b8be'
    
    def toJSON(self):
      return {"id": self.id, 
              "city": self.city,
              "street": self.street,
              "details": self.short_details(),
              "title": self.short_title(),
              "image": self.get_first_img()}

    def delete_1_image(self, im):
        bucket = storage.bucket()
        if im.internal:
            path = im.myurl.replace('https://storage.googleapis.com/diro-ac902.appspot.com/','')
            blob = bucket.blob(path)
            blob.delete()
        im.delete()
        
    def updateImages_1(self,existimg):
        # oldimg_lst = [oldimg.myurl for oldimg in self.imagedata_set.all()]
        for oldimg in self.imagedata_set.all():
            if oldimg.myurl not in existimg:
                self.delete_1_image(oldimg)

    def make_random_name(self):
        options = 'abcdefg12345hij6789r'
        newId = [options[random.randint(0, len(options)-1)] for k in range(6)]
        return ''.join(newId)
    
    def uploadImages(self,newimg):
        bucket = storage.bucket()
        for kk in range(len(newimg)):
            path = f'ad{self.id}_{self.make_random_name()}'
            while self.imagedata_set.filter(myurl__icontains = path).all():
                path = f'ad{self.id}_{self.make_random_name()}'
            blob = bucket.blob(path)
            blob.upload_from_file(newimg[kk],content_type='image/jpg')
            blob.make_public()
            url_img = blob.public_url
            if url_img: self.imagedata_set.create(myurl = url_img)

    def updateImages(self,newimg, existimg):
        self.updateImages_1(existimg)
        self.uploadImages(newimg)

    def deleteAllImages(self):
        for im in self.imagedata_set.all():
            self.delete_1_image(im)
    
    def set_update(self):
        self.update = timezone.now()
        self.save()
    
    def is_update(self):
        return timezone.now() - self.update < datetime.timedelta(hours=24)

class ImageData(models.Model): 
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    myurl = models.CharField(max_length=250)
    internal = models.BooleanField(default=True)
        
    def index(self):
        counter = 0
        for img in self.apartment.imagedata_set.order_by('id').all():
            if img == self: 
                return counter
            else: counter +=1
        return counter
    
    def __str__(self):
        return self.myurl
    
class Messages(models.Model):
    user_to = models.ForeignKey(User, on_delete=models.CASCADE) 
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(default=timezone.now)
    mes_content = models.CharField(null=False, max_length=500)
    mes_from = models.CharField(null=False, max_length=100)
    mes_contact = models.CharField(null=False, max_length=100)
    mes_read = models.BooleanField(default=False)

    def read_set(self):
        if self.mes_read: return False
        else:
            self.mes_read = True
            self.save()
            return True
    
    def get_date_format(self):
        return self.pub_date.strftime('%d/%m/%Y %H:%M')
    
    def get_new_mes(self):
        return len(self.user_to.messages_set.filter(mes_read = False).all())
    
    def get_all_mes(self):
        return self.user_to.messages_set.order_by('-id')
    
    def __str__(self):
        return self.mes_from

shutafim/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime
from django.contrib.auth.models import User
from django.http import JsonResponse
from shutafim.models import Apartment, ImageData, Messages
from django.core.mail import EmailMessage, get_connection
from django.conf import settings
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from django.utils import timezone

import random

class Recaptcha(forms.Form):
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox, label="")
    
def send_email(toemail, mysubject, mymessage):  
    with get_connection(  
        host=settings.EMAIL_HOST, 
    port=settings.EMAIL_PORT,  
    username=settings.EMAIL_HOST_USER, 
    password=settings.EMAIL_HOST_PASSWORD, 
    use_tls=settings.EMAIL_USE_TLS  
    ) as connection:  
        subject = mysubject 
        email_from = settings.EMAIL_HOST_USER  
        recipient_list = [toemail, ]  
        message = mymessage 
        EmailMessage(subject, message, email_from, recipient_list, connection=connection).send() 

def send_vaildation_email(email, name, user_id, token):
    mes = f'שלום {name}, \n תודה שנרשמת לאתר! רצינו לוודא שזה באמת המייל שלך מאחר ותוכל להגדיר שאתה מעוניין לקבל הודעות ממשתמשים שיתעניינו בדירות שתפרסם באתר.\n על מנת להשלים את תהליך ההרשמה יש ללחוץ על הקישור המופיע במייל זה. לאחר לחיצה עליו, חשבונך יופעל.\n הקישור: \n{settings.MY_URL}vaild/{user_id}/{token} \n תודה!'
    send_email(email, 'אימות כתובת המייל' ,mes)

def index(request):
    sort_val = request.GET.get('sort_val',0)
    city = request.GET.get('city_choice','')
    street = request.GET.get('street_choice','')
    rent_price_from = request.GET.get('rent_price_from','')
    rent_price_to = request.GET.get('rent_price_to','')
    gender = request.GET.get('gender',3)
    search_key = request.GET.get('search_key','')
    floor = request.GET.get('floor','')
    partners = request.GET.get('partners','')
    entry_month = request.GET.get('entry_month','')
    kosher = request.GET.get('kosher',4)
    type = request.GET.get('type',3)
    search_value = {'city': city, 'street': street, 'rent_price_from': rent_price_from, 
                    'rent_price_to': rent_price_to, 'gender':gender, 'search_key':search_key, 'entry_month':entry_month,
                    'floor':floor, 'partners':partners, 'kosher': kosher, 'type':type}
    return render(request, 'index.html', {'my_date': timezone.now().strftime('%Y-%m-%d %H:%M:%S'), 'apr':search_value, 'sort_val': int(sort_val), 'title_page':'dirot-shutafim'})

@login_required
def api(request, apr_id = -1):
    user = request.user
    if user: 
        if user.last_name != '1': return render(request, 'login.html', {'log': 'נא לאמת את כתובת המייל באמצעות מייל לאימות סיסמא שנשלח אליך בעת ההרשמה', 'title_page':'התחברות'})
    if request.method == 'POST':
        city = request.POST.get('city_choice')
        street = request.POST.get('street_choice')
        floor = request.POST.get('floor')
        gender = request.POST.get('gender')
        entry_date = request.POST.get('entey_date')
        partners = request.POST.get('partners')
        rent_price = request.POST.get('rent')
        title = request.POST.get('title')
        details = request.POST.get('details')
        kosher = request.POST.get('kosher')
        agree_mail = request.POST.get('agree_mail')
        type = request.POST.get('type')
        images, urlsexist = [], []
        for k in range(0,6):
            img = request.FILES.get('image'+str(k))
            if img: images.append(img)

        if apr_id == -1:
            
            newApr = Apartment(publisher=request.user, city = city, street=street, rent_price= rent_price, floor = floor, partners= partners, 
                                gender = gender, entry_date = entry_date, details=details, title = title, kosher = kosher, agree_mail = bool(agree_mail), type = type)
            newApr.save()
            newApr.uploadImages(images)
        elif apr_id:
            apr = Apartment.objects.filter(pk = apr_id).all()
            if apr: 
                apr = apr[0]
                if apr.publisher_id == request.user.id:
                    apr.city = city
                    apr.street=street
                    apr.rent_price= int(rent_price)
                    apr.floor = int(floor)
                    apr.partners= partners
                    apr.gender = int(gender) 
                    apr.entry_date = entry_date
                    apr.details=details
                    apr. title = title
                    apr.kosher = kosher
                    apr.agree_mail = bool(agree_mail)
                    apr.type = type
                    apr.save()
                    for k in range(0,6):
                        trp = request.POST.get(f'imagenochange{k}')
                        if trp: 
                            urlsexist.append(trp)
                    apr.updateImages(images, urlsexist)
    return redirect('myads')

@login_required
def delete_apr(request, apr_id=0):
    if apr_id:
        apr = Apartment.objects.filter(pk = apr_id).all()
        if apr:
            apr = apr[0]
            if request.method == 'POST' and apr.publisher_id == request.user.id:
                if apr.imagedata_set: 
                    try:
                        apr.deleteAllImages()
                    finally:
                        apr.delete()
    return redirect('myads')

@login_required
def newadd(request, apr_id = -1):
    user = request.user
    if user.is_authenticated: 
        if user.last_name != '1': 
            return render(request, 'login.html', {'log': 'נא לאמת את כתובת המייל באמצעות מייל לאימות סיסמא שנשלח אליך בעת ההרשמה', 'title_page':'Log-in'})
        elif request.method == 'GET':
            if apr_id >0:
                apr = Apartment.objects.filter(pk = apr_id).all()
                if apr: 
                    apr = apr[0]
                    if apr.publisher.id == user.id: return render(request, 'addmanage.html', {'apr': apr, 'rdate':apr.entry_date.strftime('%Y-%m-%d'), 'title_page':f'עריכה: {apr.title}'})
                    else: 
                        return redirect('myads')
            return render(request, 'addmanage.html', {'apr': False, 'date_d': False, 'title_page':'הוספת מודעה'})

def single_page_view(request, apr_id):
    apr = Apartment.objects.filter(pk = apr_id).all()
    if apr: 
        apr = apr[0]
        context = {'apr': apr, 'form': Recaptcha(), 'title_page':apr.title}
        return render(request, 'singlepage.html', context)
    else: return render(request, '404.html')

@login_required
def myads(request):
    user = request.user
    if user: 
        if user.last_name != '1': return render(request, 'login.html', {'log': 'נא לאמת את כתובת המייל באמצעות מייל לאימות סיסמא שנשלח אליך בעת ההרשמה', 'title_page':'Log-in'})
    return render(request, 'myads.html', {'title_page':'המודעות שלי'})

def search(request):
    updater = request.GET.get('updater',0)
    page = int(request.GET.get('page',1))
    sort_val = int(request.GET.get('sort_val',0))
    city = request.GET.get('city_choice')
    street = request.GET.get('street_choice')
    rent_price_from = request.GET.get('rent_price_from')
    rent_price_to = request.GET.get('rent_price_to')
    gender = request.GET.get('gender')
    search_key = request.GET.get('search_key')
    entry_month = request.GET.get('entry_month')
    floor = request.GET.get('floor')
    partners = request.GET.get('partners')
    kosher = request.GET.get('kosher')
    type = request.GET.get('type')
    query = Apartment.objects
    if rent_price_from: query = query.filter(rent_price__gte = int(rent_price_from))
    if rent_price_to: query = query.filter(rent_price__lte  = int(rent_price_to))
    if floor: query = query.filter(floor = floor)
    if partners: query = query.filter(partners = partners)
    if gender: 
        if int(gender) != 3: query = query.filter(gender  = int(gender))
    if kosher:
        if int(kosher) != 4: query = query.filter(kosher  = int(kosher))
    if type:
        if int(type) != 3: query = query.filter(type  = int(type))
    if entry_month: query = query.filter(entry_date__month = int(entry_month.split('-')[1])) 
    if city: 
        query = query.filter(city__iexact  = city) 
        if street: query = query.filter(street__iexact = street)
    if search_key:
        query = query.filter(details__icontains = search_key) | query.filter(title__icontains = search_key)
    
    sort_key = 'update'
    if sort_val == 2 or sort_val == 3: sort_key = 'rent_price'
    elif sort_val == 4 or sort_val == 5: sort_key = 'partners'
    elif sort_val == 6 or sort_val == 7: sort_key = 'entry_date'
    elif sort_val == 8 or sort_val == 9: sort_key = 'floor'
    if sort_val % 2 == 0: sort_key = '-'+sort_key
    if updater: query = query.filter(update__lt = datetime.strptime(updater, '%Y-%m-%d %H:%M:%S'))
    if page != -1: 
        result = query.order_by(sort_key)[12*(page - 1):12*page]
        return JsonResponse([k.toJSON() for k in result], safe=False)
    else: 
        query = query.filter(entry_date__gte = datetime.now().date())
        return JsonResponse([k.toJSON() for k in query.all()], safe=False)

def register_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        repassword = request.POST.get('repassword')
        firstname = request.POST.get('firstname')
        email = request.POST.get('email')
        msg = []
        if username:
            if len(username) < 4: msg.append('שם המשתמש צריך להכיל לפחות 4 תווים')
        if User.objects.filter(email = email).all(): msg.append('מייל זה נמצא בשימוש')

shutafim/templates/403_csrf.html
<meta http-equiv="Refresh" content="0; url='{% url 'login_page'%}" />

shutafim/templates/base.html
<!DOCTYPE html>
<html lang="he">

<head>
    <title>{% if title_page %}{{title_page}}{% else %}dirot-shutafim{% endif %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="icon" href="https://firebasestorage.googleapis.com/v0/b/diro-ac902.appspot.com/o/icon.png?alt=media&token=60827d0b-7daa-4f2c-a5df-887479e3b067">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <style>
        /* Remove the navbar's default rounded borders and increase the bottom margin */
        .navbar {
            margin-bottom: 50px;
            border-radius: 0;
        }
        
        /* Remove the jumbotron's default bottom margin */
        .jumbotron {
            margin-bottom: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row" id="articlerow">
            {% block content %}
            {% endblock %}
        </div>
    </div><br>
</body>

</html>

shutafim/templates/messages.html
{% extends "base.html" %}
{% block content %}
{% if user.messages_set.all %}
<style>
    .panel-heading {
	background-color: #7ea4c7;
	color: #fff;
}
.panel-heading:hover,
.panel-heading:focus {
	background-color: #9bc0e2;
}

.mylink:link { text-decoration: none; }


.mylink:visited { text-decoration: none; }


.mylink:hover { text-decoration: none; }


.mylink:active { text-decoration: none; }
</style>
<div class="container">
{% for msg in user.messages_set.all.first.get_all_mes %}
<div dir="rtl" class="panel-group " id="accordion">
    <a class="mylink" data-toggle="collapse" data-parent="#accordion" href="#collapse{{msg.id}}">
        <div class="panel panel-default">
      <div dir="rtl" class="panel-heading">
        <h4 style="color: white;" class="panel-title">
            {% if msg.read_set %}<span class="badge badge-pill badge-primary">חדש</span>{% endif %}
          {{msg.get_date_format}}
          <br>
          הודעה מ:
          {{msg.mes_from}}
          <br>
          פרטים ליצירת קשר: 
          {{msg.mes_contact}}
        </h4>
      </div></a>
      <div dir="rtl" id="collapse{{msg.id}}" class="panel-collapse collapse out">
        <div class="panel-body"><a href="{{msg.apartment.get_url}}">קישור למודעה</a><br>{{msg.mes_content}}</div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<p class="col-md-12" dir="rtl">לא התקבלו הודעות. אם כשערכת את המודעה לא אישרת ליצירת כפתור צור קשר, וברצונך לקבל הודעות ממעוניינים בדירה שפרסמת דרך האתר נא לאשר קבלת הודעות במסך עריכת המודעה</p>
{% endif %}
<script>
  drk = document.getElementById(`idcat_3`);
    if (drk) drk.classList.add("active")
</script>
{% endblock %}

shutafim/templates/myads.html
{% extends "base.html" %}
{% block content %}
{% if user.apartment_set.all %}
<style>
    .product-grid{
    margin-top: 10px;
    font-family: 'Poppins', sans-serif;
    text-align: center;
    border-radius: 15px;
    border: 1px solid #e7e7e7;
    overflow: hidden;
    transition: all 0.4s ease-out;
}
.product-grid:hover{ box-shadow: 5px 10px 30px rgba(0, 0, 0, 0.1); }
.product-grid .product-image{ position: relative; }
.product-grid .product-image a.image{ display: block; }
.product-grid .product-image img{
    width: 100%;
    height: 180px;
	object-fit: cover;
	object-position: 25% 25%; 
}
.product-grid .product-discount-label{
    color: #fff;
    background: #78a206;
    font-size: 14px;
    font-weight: 400;
    text-transform: uppercase;
    padding: 2px 8px;
    border-radius: 5px;
    position: absolute;
    top: 12px;
    left: 12px;
}
.product-grid .product-links{
    width: 145px;
    padding: 0;
    margin: 0;
    list-style: none;
    opacity: 0;
    transform: translateX(-50%) translateY(-50%);
    position: absolute;
    top: 65%;
    left: 50%;
    transition: all 0.4s ease 0s;
}
.product-grid:hover .product-links{
    opacity: 1;
    top: 50%;
}
.product-grid .product-links li{
    display: inline-block;
    margin: 0 2px;
}
.product-grid .product-links li a{
    color: #2c2c2c;
    background: #fff;
    font-size: 16px;
    line-height: 42px;
    width: 40px;
    height: 40px;
    border-radius: 50px;
    display: block;
    position: relative;
    transition: all 0.4s ease-out 0s;
}
.product-grid .product-links li a:hover{
    color: #fff;
    background: #78a206;
    box-shadow: 1px 1px 30px 0 rgba(0, 0, 0, 0.2);
}
.product-grid .product-links li a:before,
.product-grid .product-links li a:after{
    content: attr(data-tip);
    color: #fff;
    background-color: #555;
    font-size: 12px;
    line-height: 18px;
    padding: 5px 10px;
    white-space: nowrap;
    display: none;
    transform: translateX(-50%);
    position: absolute;
    left: 50%;
    top: -40px;
    transition: all 0.3s ease 0s;
}
.product-grid .product-links li a:after{
    content: '';
    height: 10px;
    width: 10px;
    padding: 0;
    transform: translateX(-50%) rotate(45deg);
    top: -18px;
    z-index: -1;
}
.product-grid .product-links li a:hover:before,
.product-grid .product-links li a:hover:after{
    display: block;
}
.product-grid .product-content{
    padding: 12px 12px 15px;
    position: relative;
}
.product-grid .rating{
    padding: 0;
    margin: 0 0 8px;
    list-style: none;
}
.product-grid .rating li{
    color: #78a206;
    font-size: 14px;
}
.product-grid .rating .far{ color: #808080; }
.product-grid .title{
    font-size: 18px;
    font-weight: 600;
    text-transform: uppercase;
    margin: 0 0 15px;
}
.product-grid .title a{
    color: #2c2c2c;
    transition: all 0.3s ease 0s;
}
.product-grid .title a:hover{ color: #78a206; }
.product-grid .price{
    color: #78a206;
    font-size: 17px;
    font-weight: 600;
    display: block;
    transition: all 0.4s ease-in-out;
}
.product-grid .price span{
    color: #999;
    font-weight: 500;
    text-decoration: line-through;
}
.product-grid:hover .price{ opacity: 0; }
.product-grid .add-to-cart{
    color: #fff;
    background-color: #78a206;
    font-size: 16px;
    font-weight: 500;
    text-transform: uppercase;
    line-height: 40px;
    width: 140px;
    height: 40px;
    border-radius: 50px;
    opacity: 0;
    transform: translateX(-50%);
    position: absolute;
    bottom: 50px;
    left: 50%;
    transition: all .4s ease-out;
}
.product-grid .add-to-cart:hover{ background-color: #2f2f2f; }
.product-grid:hover .add-to-cart{
    opacity: 1;
    bottom: 8px;
}
@media screen and (max-width:1200px){
    .product-grid{ margin: 0 0 30px; }
}
</style>
<div class="row col-md-12">
    {% for apr in user.apartment_set.all %}
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="{% url 'single_page_view' %}{{apr.id}}" class="image">
                    <img class="pic-1" src="{{ apr.get_first_img }}">
                </a>
                <span class="product-discount-label">{{apr.city}}</span>
            </div>
            <div class="product-content">
                <h3 dir="rtl" class="title"><a href="{% url 'single_page_view' %}{{apr.id}}">{{apr.short_title}}</a></h3>
                <p dir="rtl" class="price"> {{apr.short_details}}</p>
                <div style="display: flex; align-items: stretch; justify-content: left;">
                        <form style="flex-grow: 2; position: relative;" method="POST" action="{% url 'delete_apr' %}{{apr.id}}">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="מחיקה">
                        </form>
                        <form style="flex-grow: 3; position: relative;" method="POST" action="{% url 'renew' %}{{apr.id}}">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-primary" {% if apr.is_update %} disabled {% endif %} value="פרסום יומי">
                        </form>
                        <a style="flex-grow: 3; position: relative;" class="btn btn-primary" href="{% url 'newadd' %}{{apr.id}}">עריכה</a>

                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% else %}
<p class="col-md-12" dir="rtl">לא נמצאו מודעות.</p>
{% endif %}
<script>
    drk = document.getElementById(`idcat_4`)
    if (drk) drk.classList.add("active")
</script>
{% endblock %}

shutafim/templates/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><img height="100%" width="auto" src="https://firebasestorage.googleapis.com/v0/b/diro-ac902.appspot.com/o/logo_dirot.png?alt=media&token=b530749f-2e1f-4a02-b6f7-ab2bf87e5439"></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div> 
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li id="idcat_0"><a href="{% url 'index' %}"><span class=""></span> חיפוש דירות</a></li>
                {% if user.is_authenticated and user.last_name == '1' %}
                <li id="idcat_5"><a href="{% url 'newadd' %}"><span class=""></span>מודעה חדשה</a></li>
                <li id="idcat_4"><a href="{% url 'myads' %}"><span class=""></span>המודעות שלי</a></li>
                <li id="idcat_3"><a href="{% url 'inbox'%}"><span class=""></span> {% if user.messages_set.all.first.get_new_mes %}<span class="badge badge-light">{{user.messages_set.all.first.get_new_mes}}</span>{% endif %} {{ user.username }}</a></li>
                <li id="idcat_2"><a href="{% url 'logout_page' %}"><span class="glyphicon glyphicon-log-out"></span> Log-out</a></li>
                {% else %}
                <li id="idcat_1"><a href="{% url 'login_page' %}"><span class="glyphicon glyphicon-user"></span> Log-in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>